INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MISC_DEBUG_UTILS misc_debug_utils)

FIND_PATH(
    MISC_DEBUG_UTILS_INCLUDE_DIRS
    NAMES misc_debug_utils/api.h
    HINTS $ENV{MISC_DEBUG_UTILS_DIR}/include
        ${PC_MISC_DEBUG_UTILS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MISC_DEBUG_UTILS_LIBRARIES
    NAMES gnuradio-misc_debug_utils
    HINTS $ENV{MISC_DEBUG_UTILS_DIR}/lib
        ${PC_MISC_DEBUG_UTILS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MISC_DEBUG_UTILS DEFAULT_MSG MISC_DEBUG_UTILS_LIBRARIES MISC_DEBUG_UTILS_INCLUDE_DIRS)
MARK_AS_ADVANCED(MISC_DEBUG_UTILS_LIBRARIES MISC_DEBUG_UTILS_INCLUDE_DIRS)

